export const AffectedSide = {
    BOTH: "BOTH",
    RIGHT_SIDE: "RIGHT_SIDE",
    LEFT_SIDE: "LEFT_SIDE",
    OTHERS: "OTHERS"
  };



  export const VideoType = {
    LEARNING_HUB: "LEARNING_HUB",
    PATIENT_EXERCISE_SUPPORT: "PATIENT_EXERCISE_SUPPORT",
    CARER_EXERCISE: "CARER_EXERCISE",
  }